### ISSUE TITLE
Error handling message

### ISSUE THREAD

**Issue by niq83** [denpamusic/homeassistant-plum-ecomax#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

I get an error when the service "Set parameter" is called

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

USB to RS-485 adapter

### I'm seeing following log messages:

```shell
Error handling message: required key not provided @ data['name']. Got None (invalid_format)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you very much for the feedback!

It seems, I botched services a little bit when implementing service translations😓
Hotfix version 0.3.10 is now released and should resolve this issue.

Thanks again and sorry for any inconvenience caused!

**Comment by niq83** [comment]
Hello,
HACS does not show this last update. Does it take longer ?
Thank You !

**Comment by denpamusic** [comment]
> HACS does not show this last update. Does it take longer ?

You are right, for some reason HACS didn't pick up new tag v0.3.10 even with forced update. Normally it should've done so almost instantaneously.
I've recreated release tag and now, as far as I can see, it picks it up fine now... So weird...

To force HACS to find a new update, please open [integration page in HACS](https://my.home-assistant.io/redirect/hacs_repository/?owner=denpamusic&repository=homeassistant-plum-ecomax&category=integration), click three dots in the upper-right corner and click "Update information" or just wait for a bit until HACS eventually discovers an update by itself.

![Screenshot 2023-10-04 101028](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/2db414b4-dee0-45ff-8c8e-a5c6ff4912a8)

If it still doesn't find this update for you, feel free to write me about it. We'll try to re-release it as v0.4.1, maybe it doesn't like minors over 9 now.

**Comment by niq83** [comment]
Is there any quik way to add extra entities . Ex for parameter "airflow_power_100"  ?
Thank you

**Comment by denpamusic** [comment]
> Is there any quik way to add extra entities . Ex for parameter "airflow_power_100" ? Thank you

I assume that you want to create a box or a slider, that will allow you to change `airflow_power_100`. There's not an easy way, but possible, with some limitations:
1. Create helper [input_number integration](https://www.home-assistant.io/integrations/input_number/). Make sure to correctly fill minimum and maximum and current values, as there's no "get_parameter" service yet to get this values from the controller itself (there will be one in the next version though😉).
2. Create automation, that will watch changes of this helper entity and send them to the controller via `set_parameter` service.
You can find example for such integration in the YAML below:
```yaml
description: "Update airflow_power_100 parameter."
mode: single
trigger:
  - platform: state
    entity_id:
      - input_number.airflow_power_100
condition: []
action:
  - service: plum_ecomax.set_parameter
    data:
      name: airflow_power_100
      value: "{{ states('input_number.airflow_power_100') | float(0) }}"
    target:
      device_id: c9ea7bc95d9827402de5ad0ff7ac9490
```

`input_number.airflow_power_100` is the ID of the helper entity that you've created in first step. Also make sure to change device_id to point to your own ecoMAX device in HASS.
