### ISSUE TITLE
Can't switch off mixer pump

### ISSUE THREAD

**Issue by danielkovarik2** [denpamusic/homeassistant-plum-ecomax#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

I am not able to control mixer pump as the switch is disabled. I can turn off via work mode which turns off the pump, but when I leave it off for more than a few seconds it does reset target mixer temp to 50 celsius and does not turn on the pump back again. Is there a reason why the pump switch is disabled?

Thank you and thank you for the great integration.

<img width="319" alt="Screenshot 2023-11-09 at 9 42 42" src="https://github.com/denpamusic/homeassistant-plum-ecomax/assets/108537137/b715eeff-ac85-4a45-a025-5c417747bc16">

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### My diagnostics data:

[config_entry-plum_ecomax-f79604ccbcd8327ffc115ce04904bf03.json.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/13305943/config_entry-plum_ecomax-f79604ccbcd8327ffc115ce04904bf03.json.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback and kind words!

Firstly, lets clarify, that switch "Disable pump on thermostat" is not meant to be used to disable pump from Home Assistant (HA), it is used to tell ecoMAX (EM) to disable pump when room thermostat reaches set temperature.

Here's an excerpt from the manual for your controller:
![Excerpt from the ecoMAX 860D3-HB manual about Disable pump by thermostat parameter](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/9bae260c-9751-41b9-a34b-b583f51b30e3)

After reviewing diagnostics that you provided, I concluded that this switch is disabled, because EM860D3-HB uses different parameter table, from regular EM 8xx series. Instead of using "off_therm_pump" key as other EM 8xx, it's most likely uses "therm_mode" key to control this option. For the next version I will think of method to handle such differences.

As for disabling pump from the HA, there's sadly no way other then using work mode. If you need a switch, you can create one using HA's [template integration](https://www.home-assistant.io/integrations/switch.template/).

For example:
```yaml
switch:
  - platform: template
    switches:
      mixer_work_mode_switch:
        value_template: "{{ is_state('select.<your work mode select id>', 'heating') }}"
        turn_on:
          service: select.select_option
          data:
            option: "heating"
          target:
            entity_id: select.<your work mode select id>
        turn_off:
          service: select.select_option
          data:
            option: "off"
          target:
            entity_id: select.<your work mode select id>
```

I'll take a look at why your target mixer temp are getting reset, but it's probably how controller is supposed to operate, since this integration only sends a request to change a single parameter, when changing mixer's "Work mode". That being said, you can also use aforementioned template integration to reset target temp to required value, when turning mixer back on.

Hopefully this helps you to create a switch.

Thanks again for the feedback!
